version: '3.7'

services:
  mysql-post:
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_DATABASE: postservice_db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-post-data:/var/lib/mysql

  mysql-comment:
    image: mysql:latest
    ports:
      - '3307:3306'
    restart: always
    environment:
      MYSQL_DATABASE: commentservice_db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-comment-data:/var/lib/mysql

  mysql-review:
    image: mysql:latest
    ports:
      - '3308:3306'
    restart: always
    environment:
      MYSQL_DATABASE: reviewservice_db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-review-data:/var/lib/mysql


volumes:
  mysql-post-data:
  mysql-comment-data:
  mysql-review-data:
